# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
# when any pull happens in main automatically Job will execute

pool:
  vmImage: ubuntu-latest #windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '25.x'
    checkLatest: true

- script: npm ci
  displayName: 'Install Playwright Deps'

- script: npx playwright install chromium
  displayName: 'Install Playwright Browsers'

- script: npx playwright install-deps chromium
  displayName: 'Install Playwright system dependencies'

- script: npx playwright test
  displayName: 'Start Execution From GitRepo'

